package jchat;

/**
 *
 * @author pablonoguera
 */
public class VentanaCliente extends javax.swing.JFrame {

    // ── NUEVO: conexión y estado ──
    private java.net.Socket socket;
    private java.io.DataInputStream entrada;
    private java.io.DataOutputStream salida;
    private String miNombre;
    private int[][] miCarton = null;
    private final java.util.Set<Integer> numerosRecibidos =
        java.util.Collections.synchronizedSet(new java.util.HashSet<>());
    private boolean cartonCargado = false;

    private static final java.awt.Color COLOR_MARCADO = new java.awt.Color(52, 152, 219);
    private static final java.awt.Color COLOR_LIBRE   = new java.awt.Color(46, 204, 113);
    private static final java.awt.Color COLOR_ULTIMO  = new java.awt.Color(231, 76,  60);
    private static final java.awt.Color COLOR_NORMAL  = new java.awt.Color(236, 240, 241);
    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente() {
    initComponents();
    this.setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtextAreaMensajes = new javax.swing.JTextArea();
        txtIngreso = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablero = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        btnEnviar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtextAreaMensajes.setEditable(false);
        jtextAreaMensajes.setColumns(20);
        jtextAreaMensajes.setRows(5);
        jScrollPane1.setViewportView(jtextAreaMensajes);

        txtIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIngresoKeyPressed(evt);
            }
        });

        tablero.setBackground(new java.awt.Color(204, 204, 204));
        tablero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "B", "I", "N", "G", "o"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablero.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tablero);
        if (tablero.getColumnModel().getColumnCount() > 0) {
            tablero.getColumnModel().getColumn(0).setResizable(false);
            tablero.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablero.getColumnModel().getColumn(1).setResizable(false);
            tablero.getColumnModel().getColumn(2).setResizable(false);
            tablero.getColumnModel().getColumn(3).setResizable(false);
            tablero.getColumnModel().getColumn(4).setResizable(false);
        }

        jScrollPane2.setViewportView(listaUsuarios);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jButton1.setText("BINGOO!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        enviarMensaje();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtIngresoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresoKeyPressed
       if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) enviarMensaje();
    }//GEN-LAST:event_txtIngresoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       declararBingo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enviarMensaje() {
    String texto = txtIngreso.getText().trim();
    if (texto.isEmpty()) return;
    txtIngreso.setText("");
    try { salida.writeUTF(texto); salida.flush(); }
    catch (java.io.IOException e) { agregarChat("Error: " + e.getMessage()); }
    }

    private void pedirCarton() {
        try { salida.writeUTF("PEDIR_CARTON"); salida.flush(); }
        catch (java.io.IOException e) { agregarChat("Error al pedir cartón: " + e.getMessage()); }
    }

    private void declararBingo() {
        if (!cartonCargado) return;
        try { salida.writeUTF("BINGO:" + miNombre); salida.flush(); }
        catch (java.io.IOException e) { agregarChat("Error: " + e.getMessage()); }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> new VentanaCliente().setVisible(true));

    String nombre = javax.swing.JOptionPane.showInputDialog("Ingrese su nombre:");
    if (nombre == null || nombre.trim().isEmpty()) System.exit(0);

    VentanaCliente vc = null;
    // Esperar que la ventana esté lista
    try { Thread.sleep(500); } catch (InterruptedException ignored) {}

    try {
        java.net.Socket sfd = new java.net.Socket("localhost", 8000);
        java.io.DataInputStream ent = new java.io.DataInputStream(
            new java.io.BufferedInputStream(sfd.getInputStream()));
        java.io.DataOutputStream sal = new java.io.DataOutputStream(
            new java.io.BufferedOutputStream(sfd.getOutputStream()));

        sal.writeUTF(nombre.trim());
        sal.flush();

        // Guardar en la instancia
        for (java.awt.Window w : java.awt.Window.getWindows()) {
            if (w instanceof VentanaCliente) {
                vc = (VentanaCliente) w;
                vc.socket  = sfd;
                vc.entrada = ent;
                vc.salida  = sal;
                vc.miNombre = nombre.trim();
                break;
            }
        }

        if (vc == null) { System.out.println("Error: ventana no encontrada"); System.exit(1); }

        final VentanaCliente ventana = vc;
        new Thread(() -> ventana.escucharServidor(), "Listener").start();

    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "No se pudo conectar: " + e.getMessage());
        System.exit(1);
    }
}
    
    public static boolean isNumeric(String strNum) {
    if (strNum == null) {
        return false;
    }
    try {
        double d = Double.parseDouble(strNum);
    } catch (NumberFormatException nfe) {
        return false;
    }
    return true;
}
    
    private void escucharServidor() {
    while (true) {
        try {
            String msg = entrada.readUTF();
            if (msg.startsWith("CARTON:")) {
                parsearYMostrarCarton(msg.substring(7));
            } else if (msg.startsWith("NUMERO:")) {
                int n = Integer.parseInt(msg.substring(7).trim());
                procesarNumeroCantado(n);
            } else if (msg.startsWith("GANADOR:")) {
                mostrarGanador(msg.substring(8).trim());
            } else if (msg.startsWith("MSG:")) {
                agregarChat(msg.substring(4));
            } else {
                agregarChat(msg);
            }
        } catch (java.io.IOException e) {
            agregarChat("Conexión perdida."); break;
        }
    }
}

    private void parsearYMostrarCarton(String datos) {
        String[] filas = datos.split("\\|");
        if (filas.length != 5) return;
        miCarton = new int[5][5];
        Object[][] valores = new Object[5][5];
        for (int i = 0; i < 5; i++) {
            String[] cols = filas[i].split(",");
            for (int j = 0; j < 5; j++) {
                int num = Integer.parseInt(cols[j].trim());
                miCarton[i][j] = num;
                valores[i][j] = (num == 0) ? "★" : String.valueOf(num);
            }
        }
        javax.swing.SwingUtilities.invokeLater(() -> {
            tablero.setModel(new javax.swing.table.DefaultTableModel(
                valores, new String[]{"B","I","N","G","O"}) {
                @Override public boolean isCellEditable(int r, int c) { return false; }
            });
            aplicarRenderer();
            cartonCargado = true;
            agregarChat("¡Cartón recibido del servidor!");
        });
    }

    private void procesarNumeroCantado(int numero) {
        numerosRecibidos.add(numero);
        javax.swing.SwingUtilities.invokeLater(() -> {
            tablero.repaint();
            agregarChat("Número: " + letraDeNumero(numero) + "-" + numero);
        });
    }

    private void mostrarGanador(String ganador) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            boolean soiYo = ganador.equals(miNombre);
            javax.swing.JOptionPane.showMessageDialog(this,
                soiYo ? "¡GANASTE!" : "Ganó: " + ganador,
                "BINGO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            agregarChat("GANADOR: " + ganador);
        });
    }

    private void aplicarRenderer() {
        javax.swing.table.DefaultTableCellRenderer r = new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable t,
                    Object val, boolean sel, boolean foc, int row, int col) {
                super.getTableCellRendererComponent(t, val, sel, foc, row, col);
                setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                if (val == null) return this;
                if ("★".equals(val.toString())) { setBackground(COLOR_LIBRE); setForeground(java.awt.Color.WHITE); return this; }
                try {
                    int num = Integer.parseInt(val.toString());
                    boolean esUlt = !numerosRecibidos.isEmpty() &&
                        numerosRecibidos.stream().reduce((a,b)->b).orElse(-1) == num;
                    if (esUlt)                           { setBackground(COLOR_ULTIMO);  setForeground(java.awt.Color.WHITE); }
                    else if (numerosRecibidos.contains(num)) { setBackground(COLOR_MARCADO); setForeground(java.awt.Color.WHITE); }
                    else                                 { setBackground(COLOR_NORMAL);  setForeground(new java.awt.Color(52,73,94)); }
                } catch (NumberFormatException ignored) {}
                return this;
            }
        };
        for (int c = 0; c < 5; c++) tablero.getColumnModel().getColumn(c).setCellRenderer(r);
    }

    private void agregarChat(String msg) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            jtextAreaMensajes.append(msg + "\n");
            jtextAreaMensajes.setCaretPosition(jtextAreaMensajes.getDocument().getLength());
        });
    }

    private String letraDeNumero(int n) {
        if (n <= 15) return "B"; if (n <= 30) return "I";
        if (n <= 45) return "N"; if (n <= 60) return "G"; return "O";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTextArea jtextAreaMensajes;
    private static javax.swing.JList<String> listaUsuarios;
    private static javax.swing.JTable tablero;
    private javax.swing.JTextField txtIngreso;
    // End of variables declaration//GEN-END:variables
}
